[package]
name = "object-space-parser"
version = "0.1.0"
authors = ["Jeremy Steward <jeremy.steward@tangramvision.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
